# See config.example.yml for documentation.
object_base: orig/GPZJ01
object: sys/main.dol
hash: 00ab0f4fd4cff96b9087ed1176f9a6e839b57dde
symbols: config/GPZJ01/symbols.txt
splits: config/GPZJ01/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11

modules:
- object: files/Dr_MARIO.rel
  hash: 844cbc0479cb9a59b4aada694a0c088e1a803060
  symbols: config/GPZJ01/Dr_MARIO/symbols.txt
  splits: config/GPZJ01/Dr_MARIO/splits.txt
